version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "./.github/actions/**"
      - "./.github/workflows/**"
    schedule:
      interval: daily
    groups:
      minor-patch-versions:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 10
