---
name: xvim

path: .
windows:
  - name: code
    panes:
      - flex: 5
        commands: # each pane/window can run commands
          - command: nvim
      - flex: 2
        commands:
          - command: agent
            args:
              - --session
              - xvim

  - name: misc
    panes:
      - flex: 1
      - flex: 1
